name: Deploy Medusa Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5  # Change to your desired version

      - name: Terraform Init
        run: terraform init
        working-directory: ./medusa-terraform  # Adjust to your Terraform configuration directory

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "${PRIVATE_KEY}" > medusa.pem
          chmod 600 medusa.pem
          scp -i medusa.pem -o StrictHostKeyChecking=no -r . $USER@$HOST:/home/ubuntu/medusa
          ssh -i medusa.pem -o StrictHostKeyChecking=no $USER@$HOST 'cd /home/ubuntu/medusa && npm install && npm run start'
