name: Deploy Medusa to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > awsmedusa.pem
          chmod 600 awsmedusa.pem

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Add this if you're using DATABASE_URL
        run: |
          ssh -o StrictHostKeyChecking=no -i awsmedusa.pem ubuntu@$EC2_HOST << 'EOF'
          
            # Pull the latest changes from the repository
            git pull origin master
            
            # Optionally, restart your Medusa server here, e.g.:
            # npm install
            # npm run start
          EOF
        shell: bash
